# Generated by Django 5.0.1 on 2025-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='m3u8_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail_url',
            field=models.CharField(max_length=500),
        ),
    ]
