# Generated by Django 5.0.1 on 2025-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_episode_m3u8_url_alter_episode_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duaration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
