# Generated by Django 5.0.1 on 2025-03-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_episode_duaration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='duaration',
            new_name='duration',
        ),
    ]
