# Generated by Django 5.0.1 on 2025-03-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_duaration_episode_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsettings',
            old_name='background_image_url',
            new_name='firetv_background_image_url',
        ),
        migrations.RenameField(
            model_name='appsettings',
            old_name='splash_video_url',
            new_name='firetv_splash_video_url',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='roku_background_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='roku_splash_video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
